# Sk - Learn - GB Classifier

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
# dataset.drop(['RowNumber'],axis=1,inplace=True)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

### Data Preprocessing

In [3]:
X1 = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]

In [4]:
print(X1)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [5]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X1['e_Gender'] = le.fit_transform(X1['Gender'])

In [7]:
print(X1)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  e_Gender  
0 

One Hot Encoding the "Geography" column

In [8]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))
X = pd.get_dummies(X1, columns = ['Geography'])

In [9]:
print(X)

      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619  Female   42       2       0.00              1          1   
1             608  Female   41       1   83807.86              1          0   
2             502  Female   42       8  159660.80              3          1   
3             699  Female   39       1       0.00              2          0   
4             850  Female   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771    Male   39       5       0.00              2          1   
9996          516    Male   35      10   57369.61              1          1   
9997          709  Female   36       7       0.00              1          0   
9998          772    Male   42       3   75075.31              2          1   
9999          792  Female   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  e_Gender  Ge

### Feature Scaling

In [10]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X = sc.fit_transform(X)

In [11]:
X.drop(['Gender'],axis=1,inplace=True)

In [12]:
print(X)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  e_Gender  Geography_France  \
0                  1        101348.88         0                 1   
1        

### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

### Without hyperparameter tunning

In [15]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0).fit(X_train, y_train)

#clf.score(X_test, y_test)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrics : \n",cm)

print("Accuracy : ",accuracy_score(y_test, y_pred))

Confusion Matrics : 
 [[1507   88]
 [ 187  218]]
Accuracy :  0.8625


### With hyperparameter tunning

In [16]:
clf1 = GradientBoostingClassifier(
    loss='deviance',
    learning_rate=0.05,
    n_estimators=180,
    subsample=0.4,
    criterion='friedman_mse',
    min_samples_split=5,
    min_samples_leaf=5,
    min_weight_fraction_leaf=0.0,
    max_depth=5,
    min_impurity_decrease=0.05,
    min_impurity_split=None,
    init=None,
    random_state=2205,
    max_features=1.0,
    verbose=0,
    max_leaf_nodes=None,
    warm_start=False,
    presort='deprecated',
    validation_fraction=0.1,
    n_iter_no_change=None,
    tol=0.0001,
    ccp_alpha=0.0,
    ).fit(X_train, y_train)
y_pred = clf1.predict(X_test)
clf1.score(X_test, y_test)

cm1 = confusion_matrix(y_test, y_pred)
print("Confusion Matrics : \n",cm)

print("Accuracy : ",accuracy_score(y_test, y_pred))

Confusion Matrics : 
 [[1507   88]
 [ 187  218]]
Accuracy :  0.859


#### Input Format

In [17]:
# Male = 1, Female=0
X.iloc[0]

CreditScore             619.00
Age                      42.00
Tenure                    2.00
Balance                   0.00
NumOfProducts             1.00
HasCrCard                 1.00
IsActiveMember            1.00
EstimatedSalary      101348.88
e_Gender                  0.00
Geography_France          1.00
Geography_Germany         0.00
Geography_Spain           0.00
Name: 0, dtype: float64

#### Before model dumping

In [18]:
clf.predict([[608,42,2,0,1,1,1,101348,0,1,0,0]])

array([0], dtype=int64)

#### After model dumping

In [19]:
import joblib
 
# Save the model as a pickle in a file
joblib.dump(clf, 'churn_model.pkl')
 
# Load the model from the file
clf_model = joblib.load('churn_model.pkl')
 
# Use the loaded model to make predictions
clf_model.predict([[608,42,2,0,1,1,1,101348,0,1,0,0]])

array([0], dtype=int64)