# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
warnings.simplefilter(action='ignore', category=FutureWarning)
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
# dataset.drop(['RowNumber'],axis=1,inplace=True)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:

X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [11]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 1s 119us/sample - loss: 0.5544 - acc: 0.7526
Epoch 2/100
8000/8000 [==============================] - 0s 55us/sample - loss: 0.4567 - acc: 0.8034
Epoch 3/100
8000/8000 [==============================] - 0s 54us/sample - loss: 0.4323 - acc: 0.8144
Epoch 4/100
8000/8000 [==============================] - 0s 55us/sample - loss: 0.4218 - acc: 0.8201
Epoch 5/100
8000/8000 [==============================] - 0s 56us/sample - loss: 0.4157 - acc: 0.8219
Epoch 6/100
8000/8000 [==============================] - 0s 56us/sample - loss: 0.4123 - acc: 0.8234
Epoch 7/100
8000/8000 [==============================] - 0s 57us/sample - loss: 0.4082 - acc: 0.8259
Epoch 8/100
8000/8000 [==============================] - 0s 54us/sample - loss: 0.4055 - acc: 0.8279
Epoch 9/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.4024 - acc: 0.8

8000/8000 [==============================] - 0s 51us/sample - loss: 0.3358 - acc: 0.8634
Epoch 78/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.3353 - acc: 0.8633
Epoch 79/100
8000/8000 [==============================] - 0s 50us/sample - loss: 0.3350 - acc: 0.8629
Epoch 80/100
8000/8000 [==============================] - 0s 50us/sample - loss: 0.3350 - acc: 0.8644
Epoch 81/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.3346 - acc: 0.8645
Epoch 82/100
8000/8000 [==============================] - 0s 52us/sample - loss: 0.3347 - acc: 0.8630
Epoch 83/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.3348 - acc: 0.8639
Epoch 84/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.3340 - acc: 0.8620
Epoch 85/100
8000/8000 [==============================] - 0s 54us/sample - loss: 0.3348 - acc: 0.8637
Epoch 86/100
8000/8000 [==============================] - 0s 51us/sample - loss: 0.3341 - acc: 

## Part 3 - Making the predictions and evaluating the model

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1514   81]
 [ 198  207]]


In [21]:
from sklearn.metrics import accuracy_score
print("Accuracy : ",accuracy_score(y_test, y_pred))

Accuracy :  0.8605
